controller_list:
  - name: fake_arm_controller
    joints:
      - first_joint
      - second_joint
      - third_joint
      - fourth_joint
      - fifth_joint
  - name: fake_gripper_controller
    joints:
      - right_gripper1_joint